// Generated by react-compiler-v1 from ui-ir-v1. Do not edit by hand.
import React from 'react';
import './styles.css';

const handleSubmit = (event) => { event.preventDefault(); };
const preventNav = (event) => { event.preventDefault(); };

export default function App() {
  return (
    <main className="ui-app" aria-label={"Overview"}>
      <div className={"ui-stack ui-stack--column ui-gap--xs"}>
        <nav className={"ui-navbar ui-navbar--dark"}>
          <div className={"ui-navbar__brand"}>{"SupplyView"}</div>
        </nav>
        <div className={"ui-stack ui-stack--row"}>
          <aside className={"ui-sidebar ui-sidebar--default"}>
            <ul className={"ui-list ui-list--nav"}>
              <li>{"Overview"}</li>
              <li>{"Orders"}</li>
              <li>{"Suppliers"}</li>
              <li>{"Reports"}</li>
            </ul>
          </aside>
          <div className={"ui-stack ui-stack--column ui-gap--lg"}>
            <h1 className="ui-heading">{"Overview"}</h1>
            <div className={"ui-grid ui-grid--cols-3"}>
              <section className={"ui-card ui-card--default"}>
                <div className="ui-metric">
                  <div className="ui-metric__label">{"Open orders"}</div>
                  <div className="ui-metric__value">{"128"}</div>
                </div>
              </section>
              <section className={"ui-card ui-card--default"}>
                <div className="ui-metric">
                  <div className="ui-metric__label">{"Late shipments"}</div>
                  <div className="ui-metric__value">{"7"}</div>
                </div>
              </section>
              <section className={"ui-card ui-card--default"}>
                <div className="ui-metric">
                  <div className="ui-metric__label">{"On-time rate"}</div>
                  <div className="ui-metric__value">{"94%"}</div>
                </div>
              </section>
            </div>
            <section className={"ui-card ui-card--default"}>
              <div className={"ui-card__title"}>{"Recent orders"}</div>
              <div className="ui-table-wrap">
                <table className="ui-table">
                  <thead><tr><th scope="col">{"Order"}</th><th scope="col">{"Supplier"}</th><th scope="col">{"Status"}</th><th scope="col">{"Due"}</th></tr></thead>
                  <tbody>
                    <tr><td>{"PO-1042"}</td><td>{"Acme Metals"}</td><td>{"In transit"}</td><td>{"Oct 02"}</td></tr>
                    <tr><td>{"PO-1043"}</td><td>{"Nimbus Parts"}</td><td>{"Delayed"}</td><td>{"Oct 05"}</td></tr>
                    <tr><td>{"PO-1044"}</td><td>{"Orbit Supply"}</td><td>{"Delivered"}</td><td>{"Sep 28"}</td></tr>
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
