// Generated by react-compiler-v1 from ui-ir-v1. Do not edit by hand.
import React from 'react';
import './styles.css';

const handleSubmit = (event) => { event.preventDefault(); };
const preventNav = (event) => { event.preventDefault(); };

export default function App() {
  return (
    <main className="ui-app" aria-label={"Sign in"}>
      <div className={"ui-stack ui-stack--column ui-align--center"}>
        <section className={"ui-card ui-card--default"}>
          <form className="ui-form" onSubmit={handleSubmit}>
            <h1 className="ui-heading">{"Sign in"}</h1>
            <p className={"ui-text ui-text--muted"}>{"Welcome back. Please enter your details."}</p>
            <div className="ui-field">
              <label htmlFor={"field-1"}>{"Email *"}</label>
              <input id={"field-1"} name={"field-1"} className="ui-input" type={"email"} placeholder={"you@example.com"} required />
            </div>
            <div className="ui-field">
              <label htmlFor={"field-2"}>{"Password *"}</label>
              <input id={"field-2"} name={"field-2"} className="ui-input" type={"password"} required />
            </div>
            <div className="ui-check">
              <input id={"field-3"} name={"field-3"} type="checkbox" />
              <label htmlFor={"field-3"}>{"Remember me"}</label>
            </div>
            <button type={"submit"} className={"ui-button ui-button--primary"}>{"Sign in"}</button>
            <a className="ui-link" href="#" onClick={preventNav}>{"Forgot password?"}</a>
          </form>
        </section>
      </div>
    </main>
  );
}
