// Generated by react-compiler-v1 from ui-ir-v1. Do not edit by hand.
import React, { useState } from 'react';
import './styles.css';

function TabBar({ items, initial, variant }) {
  const [active, setActive] = useState(initial);
  return (
    <div className={"ui-tabs ui-tabs--" + variant} role="tablist">
      {items.map((item, i) => (
        <button key={i} type="button" role="tab" aria-selected={i === active}
          className={i === active ? "ui-tab ui-tab--active" : "ui-tab"} onClick={() => setActive(i)}>
          {item}
        </button>
      ))}
    </div>
  );
}

const handleSubmit = (event) => { event.preventDefault(); };
const preventNav = (event) => { event.preventDefault(); };

export default function App() {
  return (
    <main className="ui-app" aria-label={"Deliveries"}>
      <div className={"ui-stack ui-stack--column ui-gap--md"}>
        <div className={"ui-stack ui-stack--column ui-gap--xs"}>
          <h1 className="ui-heading">{"Deliveries"}</h1>
          <p className={"ui-text ui-text--muted"}>{"Tuesday, 29 Sep"}</p>
        </div>
        <div className="ui-field">
          <label htmlFor={"field-1"} className="ui-sr-only">{"Search deliveries"}</label>
          <input id={"field-1"} name={"field-1"} className="ui-input" type={"search"} placeholder={"Search by PO or supplier"} />
        </div>
        <TabBar items={["All", "Today", "Late"]} initial={0} variant={"pills"} />
        <div className={"ui-stack ui-stack--column ui-gap--sm"}>
          <section className={"ui-card ui-card--default"}>
            <div className={"ui-stack ui-stack--row ui-align--center ui-justify--between"}>
              <h3 className="ui-heading">{"PO-1042"}</h3>
              <span className={"ui-badge ui-badge--success"}>{"On time"}</span>
            </div>
            <p className={"ui-text ui-text--default"}>{"Acme Metals"}</p>
            <p className={"ui-text ui-text--muted"}>{"ETA 10:30"}</p>
          </section>
          <section className={"ui-card ui-card--default"}>
            <div className={"ui-stack ui-stack--row ui-align--center ui-justify--between"}>
              <h3 className="ui-heading">{"PO-1043"}</h3>
              <span className={"ui-badge ui-badge--error"}>{"Late"}</span>
            </div>
            <p className={"ui-text ui-text--default"}>{"Nimbus Parts"}</p>
            <p className={"ui-text ui-text--muted"}>{"ETA 13:00"}</p>
          </section>
          <section className={"ui-card ui-card--default"}>
            <div className={"ui-stack ui-stack--row ui-align--center ui-justify--between"}>
              <h3 className="ui-heading">{"PO-1047"}</h3>
              <span className={"ui-badge ui-badge--success"}>{"On time"}</span>
            </div>
            <p className={"ui-text ui-text--default"}>{"Orbit Supply"}</p>
            <p className={"ui-text ui-text--muted"}>{"ETA 15:45"}</p>
          </section>
          <section className={"ui-card ui-card--default"}>
            <div className={"ui-stack ui-stack--row ui-align--center ui-justify--between"}>
              <h3 className="ui-heading">{"PO-1051"}</h3>
              <span className={"ui-badge ui-badge--warning"}>{"At risk"}</span>
            </div>
            <p className={"ui-text ui-text--default"}>{"Delta Composites"}</p>
            <p className={"ui-text ui-text--muted"}>{"ETA 17:20"}</p>
          </section>
        </div>
        <nav className={"ui-listnav ui-listnav--tabbar"} aria-label={"tabbar"}>
          <ul className={"ui-list ui-list--tabbar"}>
            <li>{"Home"}</li>
            <li className="ui-list__item--active" aria-current="page">{"Deliveries"}</li>
            <li>{"Scan"}</li>
            <li>{"Profile"}</li>
          </ul>
        </nav>
      </div>
    </main>
  );
}
