// Generated by react-compiler-v1 from ui-ir-v1. Do not edit by hand.
import React, { useState } from 'react';
import './styles.css';

function TabBar({ items }) {
  const [active, setActive] = useState(0);
  return (
    <div className="ui-tabs" role="tablist">
      {items.map((item, i) => (
        <button key={i} type="button" role="tab" aria-selected={i === active}
          className={i === active ? "ui-tab ui-tab--active" : "ui-tab"} onClick={() => setActive(i)}>
          {item}
        </button>
      ))}
    </div>
  );
}

const handleSubmit = (event) => { event.preventDefault(); };
const preventNav = (event) => { event.preventDefault(); };

export default function App() {
  return (
    <main className="ui-app" aria-label={"Account settings"}>
      <div className={"ui-stack ui-stack--column ui-gap--md"}>
        <h1 className="ui-heading">{"Account settings"}</h1>
        <TabBar items={["Profile", "Notifications", "Security"]} />
        <section className={"ui-card ui-card--default"}>
          <form className="ui-form" onSubmit={handleSubmit}>
            <div className={"ui-grid ui-grid--cols-2"}>
              <div className="ui-field">
                <label htmlFor={"field-1"}>{"Full name"}</label>
                <input id={"field-1"} name={"field-1"} className="ui-input" type={"text"} />
              </div>
              <div className="ui-field">
                <label htmlFor={"field-2"}>{"Role"}</label>
                <select id={"field-2"} name={"field-2"} className="ui-input"><option key={0}>{"Planner"}</option></select>
              </div>
            </div>
            <div className="ui-field">
              <label htmlFor={"field-3"}>{"Bio"}</label>
              <textarea id={"field-3"} name={"field-3"} className="ui-input ui-textarea" placeholder={"Tell us about yourself"} />
            </div>
            <div className={"ui-stack ui-stack--row ui-gap--md"}>
              <button type={"button"} className={"ui-button ui-button--secondary"}>{"Cancel"}</button>
              <button type={"submit"} className={"ui-button ui-button--primary"}>{"Save changes"}</button>
            </div>
          </form>
        </section>
      </div>
    </main>
  );
}
